urlparser/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('urls.urls', namespace="index")),
]

urls/urls.py
from django.urls import path
from . import views

app_name = "urls"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.addUrl.as_view(), name="add"),
    #path("add/", views.url_create, name="add"),
]

urls/models.py
from django.db import models
import uuid

class URLItem(models.Model):
    STATUS_JOB_SEND = 0
    STATUS_JOB_DONE = 1
    STATUS_CHOICES =[(STATUS_JOB_SEND,"отправлено, результата не знаю"),(STATUS_JOB_DONE,"выполнено"),]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url = models.URLField()
    key_word = models.CharField(max_length=20)
    count_word = models.PositiveIntegerField("Количество", null=True, blank=True)
    datestamp = models.DateTimeField(verbose_name='Задача обновлена',auto_now=True)
    date_create = models.DateTimeField(verbose_name='Задача отправлена',auto_now_add=True)
    status = models.IntegerField("Статус",choices=STATUS_CHOICES, default=STATUS_JOB_SEND)

    def __str__(self):
        return self.url

    class Meta:
        ordering = ('-date_create',)
# Create your models here.

urls/forms.py
from django import forms
from urls.models import URLItem

class UrlAddForm(forms.ModelForm):
    class Meta:
        model = URLItem
        fields = ('url', "key_word")
        labels = {"url":"URL","key_word":"Слово"}

class UrlAddForm2(forms.Form):
    url = forms.URLField(label="URL", initial='', required=True)
    key_word = forms.CharField(max_length=20,label="Слово", initial='', required=True)

urls/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse
from django.http import HttpResponse
from urls.models import URLItem
from urls.forms import UrlAddForm
import time
from rq import Queue
from redis import Redis


# Create your views here.
def index(request):
    # return HttpResponse("Страница ввода URL и key_word")
    all_urls = URLItem.objects.all()
    form = UrlAddForm()
    return render(request,'urls/index.html',{"form": form,'urls':all_urls})

class addUrl(View):
    def post(self, request, *args, **kwargs):
        form = UrlAddForm(request.POST)
        if form.is_valid():
            form.save()
            all_urls = URLItem.objects.all()
        return redirect('urls:index')
        # return render(request,'urls/index.html',{"form": form,'urls':all_urls})

    def get(self, request, *args, **kwargs):
        form = URLItem()
        return render(request, "urls/index.html")

def url_create(request):
    if request.method == "POST":
        form = UrlAddForm(request.POST)
        print("url_create")
        if form.is_valid():
            cd = form.cleaned_data
            url_new = cd["url"]
            key_word_new = cd["key_word"]
            t = URLItem(url=url_new, key_word=key_word_new )
            t.save()
            redis_job(cd["url"],cd["key_word"])
            return redirect("index.html")
    else:
        form = UrlAddForm()
    return render(request, "index.html", {"form": form})
# return redirect("index.html")


def redis_job(url,word):
    r = redis.Redis()
    r.publish(url,word)

urls/templates/urls/index.html
<!--{% load static %}-->
<html>
  <head>
    <title>Статистика слов</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
  <!--<div class="container">-->
    <h1>Введите URL страницы и нужное слово для подсчета</h1>
      <form action="{% url "urls:add" %}" method="post">
        {{ form }}
        {% csrf_token %}
        <button class="add" type="submit">Обработать</button>
    </form>
  <br>
    <table>
    <tr>
        <td>ID</td><td>Create</td><td>URL</td><td>Key_word</td><td>Update</td><td>Status</td><td>Найдено</td>
    </tr>
     {% for url in urls %}
       <tr>
        <td>{{ url.id }}</td>
        <td>{{ url.date_create|date:"d.m.Y H:i:s"  }}</td>
        <td>{{ url.url }}</td>
        <td>{{ url.key_word }}</td>
        <td>{{ url.datestamp|date:"d.m.Y H:i:s" }}</td>
        {% if url.status == 0 %}
           <td>отправлено, результата не знаю</td>
        {% else %}
           <td>выполнено</td>
        {% endif %}
        {% if url.count_word %}
            <td>{{ url.key_count }}</td>
           {% else %}
                <td>----</td>
           {% endif %}
        </tr>
     {% endfor %}
</table>


  </body>

</html>